In [66]:
from unittest import result
import requests
from bs4 import BeautifulSoup
import json

result=[]
columns = ['날짜','종가', '전일비', '시가', '고가','저가','거래량']

BASE_URL = 'https://finance.naver.com/item/sise_day.naver?'

for page in range(1,11):
    parameters='code=095660&page=' + str(page)
    URL = BASE_URL + parameters
    headers={'User-Agent':'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36'}
    res = requests.get(URL,headers=headers)
    #json_data = res.json()
    soup = BeautifulSoup(res.text, 'html.parser')
    items = soup.select('.type2>tr')
    for item in items:
        try:
            item_date = item.select_one('.tah').text
            nums= item.select('.num')
            temp=[]
            for num in nums:
                #print(num.text.strip(), end='\t')

                temp.append(num.text.strip())
            result.append([item_date,*temp])
            #print()
            # temp ={
            #     '종가' : item_lastvalue,
            #     '전일비' : item_changevalue,
            #     '시가' : item_startvalue,
            #     '고가' : item_highvalue,
            #     '저가' : item_lowvlaue
            # }
        except:
            pass
        


result

[['2022.09.01', '40,600', '1,150', '39,250', '40,900', '39,050', '728,349'],
 ['2022.08.31', '39,450', '1,800', '37,400', '39,450', '36,550', '1,978,704'],
 ['2022.08.30', '37,650', '1,100', '37,850', '38,600', '36,100', '2,051,294'],
 ['2022.08.29', '38,750', '4,300', '34,250', '42,200', '34,250', '7,981,196'],
 ['2022.08.26', '34,450', '1,550', '33,350', '35,650', '32,900', '1,240,360'],
 ['2022.08.25', '32,900', '2,100', '30,800', '34,400', '30,650', '1,603,358'],
 ['2022.08.24', '30,800', '1,400', '31,450', '32,500', '28,150', '1,917,215'],
 ['2022.08.23', '29,400', '600', '29,700', '31,100', '29,200', '641,019'],
 ['2022.08.22', '30,000', '1,200', '30,750', '31,400', '30,000', '289,217'],
 ['2022.08.19', '31,200', '150', '31,100', '31,900', '30,650', '329,177'],
 ['2022.08.18', '31,050', '1,550', '29,100', '31,350', '28,650', '577,126'],
 ['2022.08.17', '29,500', '50', '29,400', '29,750', '28,650', '202,837'],
 ['2022.08.16', '29,550', '250', '29,550', '30,900', '29,300', '516,580'],
 ['2022.08.12', '29,300', '300', '28,700', '29,500', '28,350', '257,233'],
 ['2022.08.11', '29,000', '1,400', '28,150', '29,600', '27,650', '461,205'],
 ['2022.08.10', '27,600', '1,750', '29,100', '29,300', '27,350', '297,342'],
 ['2022.08.09', '29,350', '150', '29,400', '29,850', '28,500', '223,460'],
 ['2022.08.08', '29,200', '100', '29,150', '29,450', '28,250', '205,194'],
 ['2022.08.05', '29,100', '350', '29,000', '29,300', '27,550', '301,873'],
 ['2022.08.04', '28,750', '550', '28,500', '29,350', '28,250', '389,788'],
 ['2022.08.03', '28,200', '600', '27,750', '28,350', '27,250', '182,340'],
 ['2022.08.02', '27,600', '650', '27,200', '27,750', '26,700', '145,418'],
 ['2022.08.01', '26,950', '600', '27,900', '27,900', '26,750', '147,442'],
 ['2022.07.29', '27,550', '1,500', '26,250', '27,700', '26,150', '308,864'],
 ['2022.07.28', '26,050', '350', '26,650', '26,950', '26,050', '139,318'],
 ['2022.07.27', '26,400', '350', '26,200', '26,400', '25,650', '106,260'],
 ['2022.07.26', '26,050', '650', '26,650', '26,800', '26,000', '120,662'],
 ['2022.07.25', '26,700', '300', '26,350', '27,050', '26,150', '252,979'],
 ['2022.07.22', '26,400', '2,450', '28,900', '28,900', '26,100', '887,293'],
 ['2022.07.21', '28,850', '150', '29,150', '30,000', '28,600', '472,495'],
 ['2022.07.20', '29,000', '1,100', '28,300', '29,300', '27,900', '342,705'],
 ['2022.07.19', '27,900', '250', '27,450', '28,300', '27,200', '200,937'],
 ['2022.07.18', '27,650', '700', '28,500', '28,600', '27,100', '308,640'],
 ['2022.07.15', '28,350', '0', '28,100', '28,950', '28,100', '527,581'],
 ['2022.07.14', '28,350', '2,800', '26,000', '28,950', '25,900', '1,252,414'],
 ['2022.07.13', '25,550', '850', '24,350', '25,600', '24,300', '160,319'],
 ['2022.07.12', '24,700', '250', '24,700', '24,700', '23,100', '376,206'],
 ['2022.07.11', '24,950', '950', '25,900', '26,250', '24,800', '161,205'],
 ['2022.07.08', '25,900', '250', '25,800', '26,850', '25,500', '374,204'],
 ['2022.07.07', '25,650', '450', '25,600', '25,800', '24,650', '286,403'],
 ['2022.07.06', '25,200', '1,500', '23,950', '25,950', '23,350', '671,123'],
 ['2022.07.05', '23,700', '1,600', '22,200', '23,700', '22,200', '194,015'],
 ['2022.07.04', '22,100', '800', '23,000', '23,400', '21,450', '282,454'],
 ['2022.07.01', '22,900', '200', '23,350', '24,150', '22,550', '164,774'],
 ['2022.06.30', '23,100', '700', '23,500', '23,850', '22,900', '215,379'],
 ['2022.06.29', '23,800', '300', '23,700', '24,100', '23,150', '198,521'],
 ['2022.06.28', '24,100', '900', '24,750', '25,300', '23,900', '272,363'],
 ['2022.06.27', '25,000', '50', '25,300', '25,900', '24,650', '236,688'],
 ['2022.06.24', '24,950', '650', '24,200', '25,500', '24,200', '170,014'],
 ['2022.06.23', '24,300', '500', '25,050', '25,500', '24,000', '279,714'],
 ['2022.06.22', '24,800', '650', '25,550', '26,000', '24,650', '306,263'],
 ['2022.06.21', '25,450', '150', '25,550', '25,850', '23,950', '452,051'],
 ['2022.06.20', '25,300', '1,050', '26,850', '26,950', '24,500', '578,066'],
 ['2022.06.17', '26,350', '1,350', '24,500', '26,350', '23,800', '593,286'],
 ['2022.06.16', '25,000', '700', '24,650', '25,600', '24,550', '432,747'],
 ['2022.06.15', '24,300', '50', '23,900', '25,450', '23,900', '697,499'],
 ['2022.06.14', '24,250', '600', '23,300', '24,550', '23,050', '436,278'],
 ['2022.06.13', '23,650', '650', '23,800', '24,400', '22,750', '419,630'],
 ['2022.06.10', '24,300', '1,150', '22,750', '24,400', '22,450', '379,102'],
 ['2022.06.09', '23,150', '50', '23,000', '23,200', '22,600', '111,335'],
 ['2022.06.08', '23,100', '500', '22,750', '23,400', '22,400', '146,420'],
 ['2022.06.07', '22,600', '850', '23,450', '23,500', '22,500', '183,436'],
 ['2022.06.03', '23,450', '50', '23,700', '24,000', '23,350', '152,837'],
 ['2022.06.02', '23,400', '150', '23,250', '23,500', '22,750', '109,458'],
 ['2022.05.31', '23,250', '700', '22,600', '23,850', '22,250', '400,043'],
 ['2022.05.30', '22,550', '300', '22,750', '22,800', '21,950', '271,420'],
 ['2022.05.27', '22,250', '350', '22,950', '23,400', '22,150', '560,789'],
 ['2022.05.26', '21,900', '900', '21,600', '22,800', '21,450', '684,391'],
 ['2022.05.25', '21,000', '850', '20,250', '21,400', '20,200', '227,717'],
 ['2022.05.24', '20,150', '500', '20,650', '20,900', '20,150', '101,095'],
 ['2022.05.23', '20,650', '550', '20,500', '20,900', '19,950', '131,917'],
 ['2022.05.20', '20,100', '550', '19,550', '20,300', '19,550', '92,969'],
 ['2022.05.19', '19,550', '550', '19,500', '19,700', '19,200', '86,607'],
 ['2022.05.18', '20,100', '150', '20,200', '20,350', '19,850', '61,170'],
 ['2022.05.17', '19,950', '200', '19,650', '20,250', '19,650', '86,699'],
 ['2022.05.16', '19,750', '50', '19,900', '20,200', '19,600', '98,916'],
 ['2022.05.13', '19,700', '700', '19,450', '20,100', '19,350', '228,988'],
 ['2022.05.12', '19,000', '1,100', '19,800', '20,000', '18,900', '198,585'],
 ['2022.05.11', '20,100', '250', '19,700', '20,200', '19,500', '106,793'],
 ['2022.05.10', '19,850', '50', '19,300', '19,900', '18,900', '199,405'],
 ['2022.05.09', '19,800', '750', '20,400', '20,400', '19,800', '168,962'],
 ['2022.05.06', '20,550', '600', '20,650', '20,900', '20,500', '120,747'],
 ['2022.05.04', '21,150', '400', '21,700', '21,800', '21,100', '150,205'],
 ['2022.05.03', '21,550', '100', '21,850', '22,100', '21,500', '138,250'],
 ['2022.05.02', '21,650', '550', '20,600', '21,800', '20,550', '250,534'],
 ['2022.04.29', '21,100', '300', '20,900', '21,500', '20,900', '177,444'],
 ['2022.04.28', '20,800', '250', '21,250', '21,500', '20,550', '253,739'],
 ['2022.04.27', '21,050', '600', '20,650', '21,300', '20,650', '273,047'],
 ['2022.04.26', '21,650', '50', '21,800', '22,200', '21,650', '166,699'],
 ['2022.04.25', '21,700', '1,300', '22,500', '22,700', '21,650', '411,234'],
 ['2022.04.22', '23,000', '0', '22,700', '23,050', '22,550', '114,940'],
 ['2022.04.21', '23,000', '600', '23,600', '23,700', '22,900', '285,302'],
 ['2022.04.20', '23,600', '500', '24,150', '24,350', '23,400', '191,556'],
 ['2022.04.19', '24,100', '200', '23,900', '24,300', '23,900', '86,839'],
 ['2022.04.18', '23,900', '600', '24,300', '24,300', '23,800', '146,174'],
 ['2022.04.15', '24,500', '500', '24,900', '25,100', '24,250', '125,114'],
 ['2022.04.14', '25,000', '300', '25,300', '25,350', '24,850', '90,446'],
 ['2022.04.13', '25,300', '900', '24,350', '25,300', '24,250', '133,831'],
 ['2022.04.12', '24,400', '550', '24,650', '25,250', '23,700', '220,307'],
 ['2022.04.11', '24,950', '400', '25,100', '25,550', '24,950', '124,829']]

In [48]:
print(items.select_one('.tah').text)

AttributeError: ResultSet object has no attribute 'select_one'. You're probably treating a list of elements like a single element. Did you call find_all() when you meant to call find()?

AttributeError: 'list' object has no attribute 'text'

In [67]:
items

[<tr>
 <th>날짜</th>
 <th>종가</th>
 <th>전일비</th>
 <th>시가</th>
 <th>고가</th>
 <th>저가</th>
 <th>거래량</th>
 </tr>,
 <tr>
 <td colspan="7" height="8"></td>
 </tr>,
 <tr onmouseout="mouseOut(this)" onmouseover="mouseOver(this)">
 <td align="center"><span class="tah p10 gray03">2022.04.22</span></td>
 <td class="num"><span class="tah p11">23,000</span></td>
 <td class="num">
 <span class="tah p11">0</span>
 </td>
 <td class="num"><span class="tah p11">22,700</span></td>
 <td class="num"><span class="tah p11">23,050</span></td>
 <td class="num"><span class="tah p11">22,550</span></td>
 <td class="num"><span class="tah p11">114,940</span></td>
 </tr>,
 <tr onmouseout="mouseOut(this)" onmouseover="mouseOver(this)">
 <td align="center"><span class="tah p10 gray03">2022.04.21</span></td>
 <td class="num"><span class="tah p11">23,000</span></td>
 <td class="num">
 <img alt="하락" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				600
 				</span>
 </td>
 <td class="num"><span class="tah p11">23,600</span></td>
 <td class="num"><span class="tah p11">23,700</span></td>
 <td class="num"><span class="tah p11">22,900</span></td>
 <td class="num"><span class="tah p11">285,302</span></td>
 </tr>,
 <tr onmouseout="mouseOut(this)" onmouseover="mouseOver(this)">
 <td align="center"><span class="tah p10 gray03">2022.04.20</span></td>
 <td class="num"><span class="tah p11">23,600</span></td>
 <td class="num">
 <img alt="하락" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				500
 				</span>
 </td>
 <td class="num"><span class="tah p11">24,150</span></td>
 <td class="num"><span class="tah p11">24,350</span></td>
 <td class="num"><span class="tah p11">23,400</span></td>
 <td class="num"><span class="tah p11">191,556</span></td>
 </tr>,
 <tr onmouseout="mouseOut(this)" onmouseover="mouseOver(this)">
 <td align="center"><span class="tah p10 gray03">2022.04.19</span></td>
 <td class="num"><span class="tah p11">24,100</span></td>
 <td class="num">
 <img alt="상승" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				200
 				</span>
 </td>
 <td class="num"><span class="tah p11">23,900</span></td>
 <td class="num"><span class="tah p11">24,300</span></td>
 <td class="num"><span class="tah p11">23,900</span></td>
 <td class="num"><span class="tah p11">86,839</span></td>
 </tr>,
 <tr onmouseout="mouseOut(this)" onmouseover="mouseOver(this)">
 <td align="center"><span class="tah p10 gray03">2022.04.18</span></td>
 <td class="num"><span class="tah p11">23,900</span></td>
 <td class="num">
 <img alt="하락" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				600
 				</span>
 </td>
 <td class="num"><span class="tah p11">24,300</span></td>
 <td class="num"><span class="tah p11">24,300</span></td>
 <td class="num"><span class="tah p11">23,800</span></td>
 <td class="num"><span class="tah p11">146,174</span></td>
 </tr>,
 <tr>
 <td colspan="7" height="8"></td>
 </tr>,
 <tr>
 <td bgcolor="#e1e1e1" colspan="7" height="1"></td>
 </tr>,
 <tr>
 <td colspan="7" height="8"></td>
 </tr>,
 <tr onmouseout="mouseOut(this)" onmouseover="mouseOver(this)">
 <td align="center"><span class="tah p10 gray03">2022.04.15</span></td>
 <td class="num"><span class="tah p11">24,500</span></td>
 <td class="num">
 <img alt="하락" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				500
 				</span>
 </td>
 <td class="num"><span class="tah p11">24,900</span></td>
 <td class="num"><span class="tah p11">25,100</span></td>
 <td class="num"><span class="tah p11">24,250</span></td>
 <td class="num"><span class="tah p11">125,114</span></td>
 </tr>,
 <tr onmouseout="mouseOut(this)" onmouseover="mouseOver(this)">
 <td align="center"><span class="tah p10 gray03">2022.04.14</span></td>
 <td class="num"><span class="tah p11">25,000</span></td>
 <td class="num">
 <img alt="하락" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				300
 				</span>
 </td>
 <td class="num"><span class="tah p11">25,300</span></td>
 <td class="num"><span class="tah p11">25,350</span></td>
 <td class="num"><span class="tah p11">24,850</span></td>
 <td class="num"><span class="tah p11">90,446</span></td>
 </tr>,
 <tr onmouseout="mouseOut(this)" onmouseover="mouseOver(this)">
 <td align="center"><span class="tah p10 gray03">2022.04.13</span></td>
 <td class="num"><span class="tah p11">25,300</span></td>
 <td class="num">
 <img alt="상승" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				900
 				</span>
 </td>
 <td class="num"><span class="tah p11">24,350</span></td>
 <td class="num"><span class="tah p11">25,300</span></td>
 <td class="num"><span class="tah p11">24,250</span></td>
 <td class="num"><span class="tah p11">133,831</span></td>
 </tr>,
 <tr onmouseout="mouseOut(this)" onmouseover="mouseOver(this)">
 <td align="center"><span class="tah p10 gray03">2022.04.12</span></td>
 <td class="num"><span class="tah p11">24,400</span></td>
 <td class="num">
 <img alt="하락" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				550
 				</span>
 </td>
 <td class="num"><span class="tah p11">24,650</span></td>
 <td class="num"><span class="tah p11">25,250</span></td>
 <td class="num"><span class="tah p11">23,700</span></td>
 <td class="num"><span class="tah p11">220,307</span></td>
 </tr>,
 <tr onmouseout="mouseOut(this)" onmouseover="mouseOver(this)">
 <td align="center"><span class="tah p10 gray03">2022.04.11</span></td>
 <td class="num"><span class="tah p11">24,950</span></td>
 <td class="num">
 <img alt="하락" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				400
 				</span>
 </td>
 <td class="num"><span class="tah p11">25,100</span></td>
 <td class="num"><span class="tah p11">25,550</span></td>
 <td class="num"><span class="tah p11">24,950</span></td>
 <td class="num"><span class="tah p11">124,829</span></td>
 </tr>,
 <tr>
 <td colspan="7" height="8"></td>
 </tr>]